# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: 课程
    weight: 20
    identifier: courses
  - name: Golang 语言
    PageRef: course/Golang/_index.md
    weight: 10
    parent: courses
#  - name: Blog
#    PageRef: post/_index.md
#    weight: 30
