# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 100
  - name: 课程
    weight: 200
    identifier: courses
  - name: Golang
    PageRef: course/Golang/_index.md
    weight: 210
    parent: courses
  - name: Kubernetes
    PageRef: course/Kubernetes/_index.md
    weight: 220
    parent: courses
  - name: 算法/数据结构
    PageRef: course/Algorithm/_index.md
    weight: 230
    parent: courses
  - name: Leetcode
    PageRef: course/Leetcode/_index.md
    weight: 240
    parent: courses
  - name: 面试真题
    PageRef: course/Interview/_index.md
    weight: 250
    parent: courses
